apiVersion: v1
kind: ReplicationController
metadata:
  name: asecondanothertest
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: asecondanothertest
  template:
    metadata:
      labels:
        app: asecondanothertest
    spec:
      serviceAccount: YOUR
      containers:
      - name: asecondanothertest
        image: ${docker-registry}/${docker-namespace}/asecondanothertest:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080